### ISSUE TITLE
Building c2ffi with current clang

### ISSUE THREAD

**Issue by rmattes** [rpav/c2ffi#2]
Is there any chance to update c2ffi to a more recent version of clang?
On Debian/testing it's pretty much impossible to keep multiple vesions
of clang/llvm installed in parallel. A build with clang-3.4 fails:

make --no-print-directory all-recursive
Making all in src
Making all in include
Making all in c2ffi
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for`all-am'.
Making all in test
make[3]: Nothing to be done for `all'.
  CXX      c2ffi-c2ffi.o
  CXX      c2ffi-init.o
  CXX      c2ffi-options.o
In file included from ../../src/c2ffi.cpp:27:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/TextDiagnosticPrinter.h:18:
/usr/lib/llvm-3.4/include/clang/Basic/Diagnostic.h:865:44: error: expected ';' at end of declaration list
  void operator=(const DiagnosticBuilder &) LLVM_DELETED_FUNCTION;
                                           ^
                                           ;
/usr/lib/llvm-3.4/include/clang/Basic/Diagnostic.h:1226:3: error: unknown type name 'LLVM_EXPLICIT'
  LLVM_EXPLICIT operator bool() const { return Message.size() > 0; }
  ^
In file included from ../../src/c2ffi.cpp:28:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:14:
In file included from /usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:38:
/usr/lib/llvm-3.4/include/clang/Basic/FileManager.h:66:18: error: no type named 'UniqueID' in namespace 'llvm::sys::fs'
  llvm::sys::fs::UniqueID UniqueID;

``` ^
/usr/lib/llvm-3.4/include/clang/Basic/FileManager.h:76:28: error: no type named 'UniqueID' in namespace 'llvm::sys::fs'
  FileEntry(llvm::sys::fs::UniqueID UniqueID, bool IsNamedPipe, bool InPCH)
            ~~~~~~~~~~~~~~~^
/usr/lib/llvm-3.4/include/clang/Basic/FileManager.h:98:24: error: no type named 'UniqueID' in namespace 'llvm::sys::fs'
  const llvm::sys::fs::UniqueID &getUniqueID() const { return UniqueID; }
        ~~~~~~~~~~~~~~~^
In file included from ../../src/c2ffi.cpp:28:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:14:
In file included from /usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:47:
/usr/lib/llvm-3.0/include/llvm/ADT/PointerUnion.h:266:22: error: use 'template' keyword to treat 'is' as a dependent template name
      return Ty(Val).is<T>();
                     ^
                     template
/usr/lib/llvm-3.0/include/llvm/ADT/PointerUnion.h:279:22: error: use 'template' keyword to treat 'get' as a dependent template name
      return Ty(Val).get<T>();
                     ^
                     template
In file included from ../../src/c2ffi.cpp:28:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:14:
/usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:224:53: error: expected ';' at end of declaration list
    ContentCache &operator=(const ContentCache& RHS) LLVM_DELETED_FUNCTION;
                                                    ^
                                                    ;
/usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:693:47: error: expected ';' at end of declaration list
  explicit SourceManager(const SourceManager&) LLVM_DELETED_FUNCTION;
                                              ^
                                              ;
/usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:694:39: error: expected ';' at end of declaration list
  void operator=(const SourceManager&) LLVM_DELETED_FUNCTION;
                                      ^
                                      ;
In file included from ../../src/c2ffi.cpp:28:
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:141:45: error: expected ';' at end of declaration list
  CompilerInstance(const CompilerInstance &) LLVM_DELETED_FUNCTION;
                                            ^
                                            ;
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:142:43: error: expected ';' at end of declaration list
  void operator=(const CompilerInstance &) LLVM_DELETED_FUNCTION;
                                          ^
                                          ;
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:398:49: error: no member named 'isValid' in 'llvm::OwningPtr<clang::ASTConsumer>'
  bool hasASTConsumer() const { return Consumer.isValid(); }
                                       ~~~~~~~~ ^
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:416:41: error: no member named 'isValid' in 'llvm::OwningPtr<clang::Sema>'
  bool hasSema() const { return TheSema.isValid(); }
                                ~~~~~~~ ^
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:437:31: error: no member named 'isValid' in 'llvm::OwningPtr<clang::CodeCompleteConsumer>'
    return CompletionConsumer.isValid();
           ~~~~~~~~~~~~~~~~~~ ^
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:460:56: error: no member named 'isValid' in 'llvm::OwningPtr<llvm::Timer>'
  bool hasFrontendTimer() const { return FrontendTimer.isValid(); }
                                         ~~~~~~~~~~~~~ ^
In file included from ../../src/c2ffi.cpp:33:
In file included from /usr/lib/llvm-3.4/include/clang/Lex/HeaderSearch.h:17:
In file included from /usr/lib/llvm-3.4/include/clang/Lex/DirectoryLookup.h:19:
/usr/lib/llvm-3.4/include/clang/Lex/ModuleMap.h:99:5: error: unknown type name 'LLVM_EXPLICIT'
    LLVM_EXPLICIT operator bool() const { return Storage.getPointer() != 0; }
    ^
In file included from ../../src/c2ffi.cpp:33:
/usr/lib/llvm-3.4/include/clang/Lex/HeaderSearch.h:236:36: error: expected ';' at end of declaration list
  HeaderSearch(const HeaderSearch&) LLVM_DELETED_FUNCTION;
                                   ^
                                   ;
/usr/lib/llvm-3.4/include/clang/Lex/HeaderSearch.h:237:38: error: expected ';' at end of declaration list
  void operator=(const HeaderSearch&) LLVM_DELETED_FUNCTION;
                                     ^
                                     ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
In file included from ../../src/init.cpp:27:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/TextDiagnosticPrinter.h:18:
/usr/lib/llvm-3.4/include/clang/Basic/Diagnostic.h:865:44: error: expected ';' at end of declaration list
  void operator=(const DiagnosticBuilder &) LLVM_DELETED_FUNCTION;
                                           ^
                                           ;
In file included from ../../src/options.cpp:27:
In file included from ../../src/include/c2ffi.h:96:
In file included from ../../src/include/c2ffi/type.h:30:
In file included from /usr/lib/llvm-3.4/include/clang/AST/Type.h:17:
In file included from /usr/lib/llvm-3.4/include/clang/AST/NestedNameSpecifier.h:17:
/usr/lib/llvm-3.4/include/clang/Basic/Diagnostic.h:865:44: error: expected ';' at end of declaration list
  void operator=(const DiagnosticBuilder &) LLVM_DELETED_FUNCTION;
                                           ^
                                           ;
/usr/lib/llvm-3.4/include/clang/Basic/Diagnostic.h:1226:3: error: unknown type name 'LLVM_EXPLICIT'
  LLVM_EXPLICIT operator bool() const { return Message.size() > 0; }
  ^
/usr/lib/llvm-3.4/include/clang/Basic/Diagnostic.h:1226:3: error: unknown type name 'LLVM_EXPLICIT'
  LLVM_EXPLICIT operator bool() const { return Message.size() > 0; }
  ^
In file included from ../../src/options.cpp:27:
In file included from ../../src/include/c2ffi.h:96:
In file included from ../../src/include/c2ffi/type.h:30:
In file included from /usr/lib/llvm-3.4/include/clang/AST/Type.h:17:
/usr/lib/llvm-3.4/include/clang/AST/NestedNameSpecifier.h:100:46: error: expected ';' at end of declaration list
  void operator=(const NestedNameSpecifier &) LLVM_DELETED_FUNCTION;
                                             ^
                                             ;
/usr/lib/llvm-3.4/include/clang/AST/NestedNameSpecifier.h:234:3: error: unknown type name 'LLVM_EXPLICIT'
  LLVM_EXPLICIT operator bool() const { return Qualifier; }
  ^
/usr/lib/llvm-3.4/include/clang/AST/NestedNameSpecifier.h:255:37: error: expected ';' at end of declaration list
  SourceRange getSourceRange() const LLVM_READONLY;
                                    ^
                                    ;
/usr/lib/llvm-3.4/include/clang/AST/NestedNameSpecifier.h:437:37: error: expected ';' at end of declaration list
  SourceRange getSourceRange() const LLVM_READONLY {
                                    ^
                                    ;
In file included from ../../src/options.cpp:27:
In file included from ../../src/include/c2ffi.h:96:
In file included from ../../src/include/c2ffi/type.h:30:
In file included from /usr/lib/llvm-3.4/include/clang/AST/Type.h:18:
In file included from /usr/lib/llvm-3.4/include/clang/AST/TemplateName.h:20:
/usr/lib/llvm-3.0/include/llvm/ADT/PointerUnion.h:266:22: error: use 'template' keyword to treat 'is' as a dependent template name
      return Ty(Val).is<T>();
                     ^
                     template
/usr/lib/llvm-3.0/include/llvm/ADT/PointerUnion.h:279:22: error: use 'template' keyword to treat 'get' as a dependent template name
      return Ty(Val).get<T>();
                     ^
                     template
In file included from ../../src/options.cpp:27:
In file included from ../../src/include/c2ffi.h:96:
In file included from ../../src/include/c2ffi/type.h:30:
In file included from /usr/lib/llvm-3.4/include/clang/AST/Type.h:21:
/usr/lib/llvm-3.4/include/clang/Basic/IdentifierTable.h:79:40: error: expected ';' at end of declaration list
  IdentifierInfo(const IdentifierInfo&) LLVM_DELETED_FUNCTION;
                                       ^
                                       ;
/usr/lib/llvm-3.4/include/clang/Basic/IdentifierTable.h:80:40: error: expected ';' at end of declaration list
  void operator=(const IdentifierInfo&) LLVM_DELETED_FUNCTION;
                                       ^
                                       ;
/usr/lib/llvm-3.4/include/clang/Basic/IdentifierTable.h:358:49: error: expected ';' at end of declaration list
  IdentifierIterator(const IdentifierIterator &) LLVM_DELETED_FUNCTION;
                                                ^
                                                ;
/usr/lib/llvm-3.4/include/clang/Basic/IdentifierTable.h:359:45: error: expected ';' at end of declaration list
  void operator=(const IdentifierIterator &) LLVM_DELETED_FUNCTION;
                                            ^
                                            ;
/usr/lib/llvm-3.4/include/clang/Basic/IdentifierTable.h:721:39: error: expected ';' at end of declaration list
  SelectorTable(const SelectorTable &) LLVM_DELETED_FUNCTION;
                                      ^
                                      ;
/usr/lib/llvm-3.4/include/clang/Basic/IdentifierTable.h:722:40: error: expected ';' at end of declaration list
  void operator=(const SelectorTable &) LLVM_DELETED_FUNCTION;
                                       ^
                                       ;
In file included from ../../src/init.cpp:28:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:14:
In file included from /usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:38:
/usr/lib/llvm-3.4/include/clang/Basic/FileManager.h:66:18: error: no type named 'UniqueID' in namespace 'llvm::sys::fs'
  llvm::sys::fs::UniqueID UniqueID;
  ~~~~~~~~~~~~~~~^
/usr/lib/llvm-3.4/include/clang/Basic/FileManager.h:76:28: error: no type named 'UniqueID' in namespace 'llvm::sys::fs'
  FileEntry(llvm::sys::fs::UniqueID UniqueID, bool IsNamedPipe, bool InPCH)
            ~~~~~~~~~~~~~~~^
/usr/lib/llvm-3.4/include/clang/Basic/FileManager.h:98:24: error: no type named 'UniqueID' in namespace 'llvm::sys::fs'
  const llvm::sys::fs::UniqueID &getUniqueID() const { return UniqueID; }
        ~~~~~~~~~~~~~~~^
In file included from ../../src/init.cpp:28:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:14:
In file included from /usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:47:
/usr/lib/llvm-3.0/include/llvm/ADT/PointerUnion.h:266:22: error: use 'template' keyword to treat 'is' as a dependent template name
      return Ty(Val).is<T>();
                     ^
                     template
/usr/lib/llvm-3.0/include/llvm/ADT/PointerUnion.h:279:22: error: use 'template' keyword to treat 'get' as a dependent template name
      return Ty(Val).get<T>();
                     ^
                     template
In file included from ../../src/init.cpp:28:
In file included from /usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:14:
/usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:224:53: error: expected ';' at end of declaration list
    ContentCache &operator=(const ContentCache& RHS) LLVM_DELETED_FUNCTION;
                                                    ^
                                                    ;
In file included from ../../src/options.cpp:27:
In file included from ../../src/include/c2ffi.h:96:
In file included from ../../src/include/c2ffi/type.h:30:
/usr/lib/llvm-3.4/include/clang/AST/Type.h:444:3: error: unknown type name 'LLVM_EXPLICIT'
  LLVM_EXPLICIT operator bool() const { return hasQualifiers(); }
  ^
/usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:693:47: error: expected ';' at end of declaration list
  explicit SourceManager(const SourceManager&) LLVM_DELETED_FUNCTION;
                                              ^
                                              ;
/usr/lib/llvm-3.4/include/clang/Basic/SourceManager.h:694:39: error: expected ';' at end of declaration list
  void operator=(const SourceManager&) LLVM_DELETED_FUNCTION;
                                      ^
                                      ;
/usr/lib/llvm-3.4/include/clang/AST/Type.h:1167:21: error: expected ';' at end of declaration list
  Type(const Type &) LLVM_DELETED_FUNCTION;
                    ^
                    ;
/usr/lib/llvm-3.4/include/clang/AST/Type.h:1168:31: error: expected ';' at end of declaration list
  void operator=(const Type &) LLVM_DELETED_FUNCTION;
                              ^
                              ;
/usr/lib/llvm-3.4/include/clang/AST/Type.h:4585:5: error: cannot initialize object parameter of type 'clang::Qualifiers' with an expression of type 'clang::QualifierCollector'
    addFastQualifiers(type.getLocalFastQualifiers());
    ^~~~~~~~~~~~~~~~~
/usr/lib/llvm-3.4/include/clang/AST/Type.h:4590:5: error: cannot initialize object parameter of type 'clang::Qualifiers' with an expression of type 'clang::QualifierCollector'
    addConsistentQualifiers(extQuals->getQualifiers());
    ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../src/init.cpp:28:
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:141:45: error: expected ';' at end of declaration list
  CompilerInstance(const CompilerInstance &) LLVM_DELETED_FUNCTION;
                                            ^
                                            ;
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:142:43: error: expected ';' at end of declaration list
  void operator=(const CompilerInstance &) LLVM_DELETED_FUNCTION;
                                          ^
                                          ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:398:49: error: no member named 'isValid' in 'llvm::OwningPtr<clang::ASTConsumer>'
  bool hasASTConsumer() const { return Consumer.isValid(); }
                                       ~~~~~~~~ ^
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:416:41: error: no member named 'isValid' in 'llvm::OwningPtr<clang::Sema>'
  bool hasSema() const { return TheSema.isValid(); }
                                ~~~~~~~ ^
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:437:31: error: no member named 'isValid' in 'llvm::OwningPtr<clang::CodeCompleteConsumer>'
    return CompletionConsumer.isValid();
           ~~~~~~~~~~~~~~~~~~ ^
/usr/lib/llvm-3.4/include/clang/Frontend/CompilerInstance.h:460:56: error: no member named 'isValid' in 'llvm::OwningPtr<llvm::Timer>'
  bool hasFrontendTimer() const { return FrontendTimer.isValid(); }
                                         ~~~~~~~~~~~~~ ^
In file included from ../../src/init.cpp:34:
In file included from /usr/lib/llvm-3.4/include/clang/Lex/HeaderSearch.h:17:
In file included from /usr/lib/llvm-3.4/include/clang/Lex/DirectoryLookup.h:19:
/usr/lib/llvm-3.4/include/clang/Lex/ModuleMap.h:99:5: error: unknown type name 'LLVM_EXPLICIT'
    LLVM_EXPLICIT operator bool() const { return Storage.getPointer() != 0; }
    ^
In file included from ../../src/init.cpp:34:
/usr/lib/llvm-3.4/include/clang/Lex/HeaderSearch.h:236:36: error: expected ';' at end of declaration list
  HeaderSearch(const HeaderSearch&) LLVM_DELETED_FUNCTION;
                                   ^
                                   ;
/usr/lib/llvm-3.4/include/clang/Lex/HeaderSearch.h:237:38: error: expected ';' at end of declaration list
  void operator=(const HeaderSearch&) LLVM_DELETED_FUNCTION;
                                     ^
                                     ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [c2ffi-c2ffi.o] Error 1
make[3]: *** Waiting for unfinished jobs....
20 errors generated.
make[3]: *** [c2ffi-options.o] Error 1
20 errors generated.
make[3]: *** [c2ffi-init.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

TIA, Ralf Mattes
```
